language: c
sudo: false

before_script:
    - gcc --version
    - echo $LC_ALL

matrix:
  include:
    - os: linux
      compiler:
        - gcc

script:
    - make -j4

notification:
  email: false
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
